package sec1;

import java.io.DataInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.net.ServerSocket;
import java.net.Socket;
import java.security.Key;

import javax.crypto.Cipher;

public class CipherServer
{
	public static void main(String[] args) throws Exception 
	{
		int port = 7998;
		ServerSocket server = new ServerSocket(port);
		Socket s = server.accept();
		System.out.println("Server is listening at 127.0.0.1:7998");
		ObjectInputStream is = new ObjectInputStream(s.getInputStream());
		
		byte[] resultBuff=new byte[2048];
		resultBuff=(byte[]) is.readObject();
		System.out.println(new String(resultBuff));
		// YOU NEED TO DO THESE STEPS:
		// -Read the key from the file generated by the client.
		File f = new File("DESKEY.txt");
	    FileInputStream fis = new FileInputStream(f);
	    Key key;
	    ObjectInputStream oin = new ObjectInputStream(fis);
	    try {
	      key = (Key) oin.readObject();
	    } finally {
	      oin.close();
	    }  
		// -Use the key to decrypt the incoming message from socket s.	
		// Get a cipher object.
		Cipher cipher = Cipher.getInstance("DES/ECB/PKCS5Padding");
		cipher.init(Cipher.DECRYPT_MODE, key);
		//decode the message
		byte[] stringBytes = cipher.doFinal(resultBuff);
	 
		//converts the decoded message to a String
		String clear = new String(stringBytes, "UTF8");
		// -Print out the decrypt String to see if it matches the orignal message.
		System.out.println(clear);
	}
}